-- SUPERSEDED
-- Do not run this file for exact StockGPT trade levels.
-- Exact values must come from the app trade-plan calculation used by the stock page Suggested Levels card.
-- If the old trigger was already applied, run supabase/remove_portfolio_entry_trade_level_trigger.sql.
